---
title: "Assignment07"
author: "Max Selvaggio"
date: "2022-07-31"
output:
 html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(gamlr)

```


```{r}
setwd("C:\\Users\\mselv\\Documents\\GitHub\\ECO5445SU22\\Assignment06\\data")
prices <- read.csv("prop_prices_reduced.csv")

```

Number 1

```{r}
set.seed(1234)
train <- sample(nrow(prices), 0.9*nrow(prices))

prices.train <- prices[train,]
prices.validate <- prices[-train,]
```

Number 2

```{r}
model <- lm(sale_def ~ bed + bath + area_heated + area + 
              dist_cbd + dist_lakes + pool, data = prices.train)
summary(model)

modelpred <- predict(model,prices.validate)
modelactual <- prices.validate$sale_def

```

Number 3

```{r}
x <- data.matrix(prices.train[, c('bed', 'bath', 'area_heated', 'area', 
                                  'dist_cbd', 'dist_lakes')])

y <- prices.train$sale_def
ym <- as.matrix(y)

Lass <- gamlr(x, log(ym), verb=TRUE)
summary(Lass)

B <- coef(Lass)

B <- B[-1,]

```

Number 4

```{r}
cvLass <- cv.gamlr(x, log(ym), nfold = 10, verb=TRUE)
summary(cvLass)

```

Number 5

```{r}
log(Lass$lambda[which.min(AICc(Lass))])
log(Lass$lambda[which.min(AIC(Lass))])
log(Lass$lambda[which.min(BIC(Lass))])
log(cvLass$lambda.min)
log(cvLass$lambda.1se)



sqrt(mean((modelactual - modelpred)^2))
```

